Django/wumpworld/blog/urls.py
from django.conf.urls import include, url
from . import views
from django.views.generic.base import TemplateView
from unidecode import unidecode

app_name = 'blog'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='main'),
    url(r'^post/(?P<slug>[^\.]+)/$', views.DetailView.as_view(), name='post-detail'),
    url(r'^category/(?P<category>[^\.]+)/$', views.CategoryIndexView.as_view(), name='category-index'),
    url(r'^tag/(?P<tag>[^\.]+)/$', views.TagIndexView.as_view(), name='tag-index'),
]

Django/wumpworld/userprofile/urls.py
from django.conf.urls import include, url
from . import views
from django.views.generic.base import TemplateView
from django.views.generic.base import RedirectView

app_name = 'userprofile'
urlpatterns = [
    url(r'^(?P<username>\w+)$', views.profile_view, name='main'),
    url(r'^(?P<username>\w+)/edit$', views.profile_edit, name='edit'),
]

Django/wumpworld/wumpworld/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from . import views
from django.views.generic.base import TemplateView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='home.html'), name='home'),
    url(r'^login/$', auth_views.login, {'template_name': 'login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'template_name': 'logged_out.html'}, name='logout'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^profile/', include('userprofile.urls')),
    url(r'^blog/', include('blog.urls')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django/wumpworld/blog/models.py
from __future__ import unicode_literals
from django.contrib.auth.models import User
import datetime
from django.utils import timezone
from taggit.managers import TaggableManager
from taggit.models import TaggedItemBase

from django.db import models


class PostTag(TaggedItemBase):
    content_object = models.ForeignKey('Post')


def blog_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return 'blog/post_{0}/featured-{1}'.format(instance.id, filename)

class Post(models.Model):
    title = models.CharField(max_length=100)
    featured_img = models.FileField(upload_to=blog_directory_path, max_length=100)
    pub_date = models.DateTimeField(auto_now_add=True, db_index=True)
    updated = models.DateTimeField(auto_now=True, db_index=True)
    author = models.ForeignKey(User)
    body = models.TextField()
    category = models.ForeignKey('blog.Category')
    tags = TaggableManager(through=PostTag)
    slug = models.SlugField(max_length=100, unique=True)

    def __unicode__(self):
       return self.title+', '+self.pub_date.strftime('%Y-%m-%d %H:%M')

    @models.permalink
    def get_absolute_url(self):
        return 'blog:post', (self.slug,)

class Category(models.Model):
    title = models.CharField(max_length=100, db_index=True)
    description = models.TextField(blank=True)
    slug = models.SlugField(max_length=100, db_index=True)

    def __unicode__(self):
       return self.title

    class Meta:
        verbose_name_plural = "categories"

Django/wumpworld/userprofile/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.conf import settings

def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return 'users/user_{0}/profile-pic-{1}'.format(instance.user.id, filename)
 
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_pic = models.FileField(upload_to=user_directory_path, max_length=100)
    bio = models.TextField(max_length=500, blank=True)
    location = models.CharField(max_length=30, blank=True)
    birth_date = models.DateField(null=True, blank=True)
    pub_date = models.DateTimeField(auto_now_add=True)
    last_updated = models.DateTimeField(auto_now=True)

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

Django/wumpworld/userprofile/forms.py
from django import forms
from models import Profile

class ProfileForm(forms.ModelForm):
	profile_pic = forms.FileField(widget=forms.ClearableFileInput(attrs={'class' : 'form-control-file'}))
	bio = forms.CharField(widget=forms.Textarea(attrs={'class' : 'form-control'}))
	location = forms.CharField(widget=forms.TextInput(attrs={'class' : 'form-control'}))
	birth_date = forms.DateField(widget=forms.DateInput(attrs={'class' : 'form-control'}))

	class Meta:
		model = Profile
		fields = ['profile_pic', 'bio', 'location', 'birth_date'] 

Django/wumpworld/blog/views.py
from django.shortcuts import render
from django.views.generic import ListView
from .models import Post, Category
from django.shortcuts import render_to_response, get_object_or_404
from django.utils import timezone
from django.views import generic
from django.core.paginator import Paginator

class IndexView(ListView):
    model = Post
    template_name = "post-index.html"

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['page_title'] = "All posts"
        context['category_list'] = Category.objects.all()
        context['complete_list'] = Post.objects.all().order_by('-pub_date')
        paginator = Paginator(context['complete_list'], 10)
        context['object_list'] = paginator.page(1)
        return context

class CategoryIndexView(ListView):
    model = Post
    template_name = "post-index.html"
    def get_context_data(self, **kwargs):
        context = super(CategoryIndexView, self).get_context_data(**kwargs)
        category = Category.objects.get(slug=self.kwargs['category'])
        context['page_title'] = category.title+" Posts"
        context['object_list'] = Post.objects.filter(category=category).order_by('-pub_date')
        context['category_list'] = Category.objects.all()
        return context

class TagIndexView(ListView):
	model = Post
 	template_name = "post-index.html"
 	def get_context_data(self, **kwargs):
 		context = super(TagIndexView, self).get_context_data(**kwargs)
 		context['page_title'] = " Posts tagged "+self.kwargs['tag']
 		context['object_list'] = Post.objects.filter(tags__name__in=[self.kwargs['tag']]).order_by('-pub_date')
 		context['category_list'] = Category.objects.all()
 		return context

class DetailView(generic.DetailView):
    model = Post
    template_name = 'post.html'

Django/wumpworld/userprofile/views.py
from django.shortcuts import render
from django.views.generic.edit import UpdateView
from userprofile.models import Profile
from .forms import ProfileForm
from django.views import generic
from django.contrib.auth.models import User
from django.http import Http404
from django.shortcuts import redirect 

def profile_view(request, username):
    try:
        u = User.objects.get(username=username)
        p = Profile.objects.get(user=u)
    except User.DoesNotExist:
        raise Http404("User does not exist")
    return render(request, 'profile.html', {'u': u})

def profile_edit(request, username): 
    u = User.objects.get(username=username)
    p = Profile.objects.get(user=u)
    form = ProfileForm(request.POST or None, instance=p)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect("/profile/"+username)
        else:
            return HttpResponse('Error!')
    if not request.user.username == username:
        return redirect("/profile/"+username) 
    return render(request, 'edit.html', {'page_title': "Edit Profile", 'cancel_url': "/profile/"+username, 'form': form, 'submit_text': "Save"})

Django/wumpworld/wumpworld/views.py
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect
from django.views.generic.base import TemplateView
from django.views.generic import View
from django.http import HttpResponse
import json

def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('home')
    else:
        form = UserCreationForm()
    return render(request, 'signup.html', {'form': form})

Django/wumpworld/templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
  <link rel="stylesheet" href="{% static '/css/style.css' %}" type="text/css" />
  <link rel="stylesheet" href="{% static '/css/bootstrap.min.css' %}" type="text/css" />
  
  <script src="{% static '/js/bootstrap.min.js' %}"></script>
  <script src="{% static '/js/jquery.js' %}"></script>
  <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>

  <title>{% block title %} Wump World {%endblock%}</title>
</head>

<body>
    {% with url_name=request.resolver_match.url_name %}
    <nav class="navbar navbar-toggleable-md navbar-light">
      <div class="container">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{% url 'home' %}">WW</a>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="#">Link 1</a>
            </li>

            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Dropown
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <li>
                  <a class="dropdown-item" href="#">Item1</a>
                </li>
                <li>
                  <a class="dropdown-item" href="#">Item2</a>
                </li>
              </ul>
            </li>

            <li class="nav-item {% if url_name == 'blog:main' %}active{% endif %}">
              <a class="nav-link" href="{% url 'blog:main' %}">Blog</a>
            </li>
          </ul>

          <ul class="navbar-nav pull-right"> 
            {% if user.is_authenticated %}
            <li class="nav-item"> 
              <a class="nav-link" href="{% url 'userprofile:main' user.username %}"> Hi, {{ user.username }}! </a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="{% url 'userprofile:main' user.username %}" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <img class="icon" src="{% static '/images/icons/noun-user.png' %}"/>
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <li>
                  <a class="dropdown-item" href="{% url 'userprofile:main' user.username %}">Profile </a>
                </li>
                <li class="nav-item">
                  <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                </li>
              </ul>
            </li>

            {% else %}
            <li>
              <a class="nav-link" href="{% url 'login' %}">Login</a>
            </li>
            <li>
              <a class="nav-link" href="{% url 'signup' %}">Sign up</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
    {% endwith %}
    
    <div class="main container">
      <div class="row page-header"> 
        <div class="col-md-12">
          <h1 class="page-title">{% block page-title %}{% endblock %}</h1>
          <span class="page-options"> {% block page-options %}{% endblock %}</span>
        </div>
      </div>
      <div class="page-content"> 
        {% block content %}
        {% endblock %}
      </div>
    </div>

    <footer class="footer">
      <div class="container">
        <p class="text-muted"> &#169; WW</p>
      </div>
    </footer>

</body>
</html>

Django/wumpworld/templates/edit.html
{% extends 'base.html' %}

{% block page-title %} {{ page_title|title }} {% endblock %}
{% block content %}
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.8/jquery.min.js"></script>
<form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
    {{ form.media }}
    {{ form.as_p }}
    <a class="btn btn-info" role="button" href="{{cancel_url}}">Cancel</a>
    <input class="btn btn-info" type="submit" value="{{ submit_text }}"/>
</form>

{% endblock %}

Django/wumpworld/templates/home.html
{% extends 'base.html' %}

{% block page-title %}Home{% endblock %}

{% block content %}
  <p>Home</p>
{% endblock %}

Django/wumpworld/templates/logged_out.html
{% extends 'base.html' %}

{% block page-title %}Logged out<{% endblock %}

{% block content %}
  <h2>See you later!</h2>
  <p>You have been successfully logged out.</p>
  <p><a href="{% url 'login' %}">Log in</a> again.</p>
{% endblock %}

Django/wumpworld/templates/login.html
{% extends 'base.html' %}

{% block page-title %}Login{% endblock %}

{% block content %}
  <h2>Login</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
  </form>
{% endblock %}

Django/wumpworld/templates/post-index.html
{% extends 'base.html' %}

{% block page-title %} 
	{{page_title}} 
{% endblock %}

{% block page-breadcrumbs %} 
{% endblock %}

{% block page-options %} 
	
{% endblock %}

{% block content %}
	{% for category in category_list %}
		<a href="{% url 'blog:category-index' category.slug%}">{{category.title}}</a>
	{%endfor%}

	{% if object_list %}
    	{% for post in object_list %}
			
			<div class="card blog-post-card">
				  <div class="row">

				  	<div class="col-md-4 no-padding-right">
				  		<div style="background: url(/media/{{post.featured_img}}) center no-repeat;" class="card-img-bottom"></div>
			         </div>

			        <div class="col-md-8">

			          <div class="card-block">
			          	<small> <a href="{% url 'blog:category-index' post.category.slug%}"> {{post.category.title}}</a></small>
			            <h4 class="card-title">{{post.title}}</h4>
			            <p class="card-text">
			            	<span class="text-muted">{{post.pub_date}} | by {{post.author.username}}</span>
			            </p>
						{% for tag in post.tags.all %} <a class="btn btn-secondary post-tag" href="{% url 'blog:tag-index' tag.slug %}">{{tag}}</a>{% endfor %} 
						<p class="card-text">{{post.body|truncatechars:200}}</p>
			            <a href="{% url 'blog:post-detail' post.slug %}" class="btn btn-info">Read More</a>
			          </div>


			        </div>
			      </div>
				</div>


		{%endfor%}
		{% if object_list.has_other_pages %}
		  <ul class="pagination">
		    {% if object_list.has_previous %}
		      <li><a href="?page={{ object_list.previous_page_number }}">&laquo;</a></li>
		    {% else %}
		      <li class="disabled"><span>&laquo;</span></li>
		    {% endif %}
		    {% for i in object_list.paginator.page_range %}
		      {% if object_list.number == i %}
		        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
		      {% else %}
		        <li><a href="?page={{ i }}">{{ i }}</a></li>
		      {% endif %}
		    {% endfor %}
		    {% if object_list.has_next %}
		      <li><a href="?page={{ object_list.next_page_number }}">&raquo;</a></li>
		    {% else %}
		      <li class="disabled"><span>&raquo;</span></li>
		    {% endif %}
		  </ul>
		{% endif %}
	{% else %}
    <p>None available.</p>
	{%endif%}



{% endblock %}

Django/wumpworld/templates/post.html
{% extends 'base.html' %}

{% block page-title %} 
	{{post.title}} 
{% endblock %}

{% block page-options %} 
{% endblock %}

{% block content %}
	<div class="row"> 
		<div class="col-md-8 post-main">
			<div class="post-metadata">
				<div class="text-muted">{{post.pub_date}} | by {{post.author.username}}</div>
				<a href="#"> {{post.category.title}}</a>
			</div>
			{{post.body}}
		</div>
		<div class="col-md-4 post-sidebar">
		</div>
	</div>

{% endblock %}

Django/wumpworld/templates/profile.html
{% extends 'base.html' %}

{% block page-title %} 
	{{u.username}} 
{% endblock %}

{% block page-breadcrumbs %} 
{% endblock %}

{% block page-options %} 
	{% if user.username == u.username %}
		<a class="btn btn-info" role="button" href="{% url 'userprofile:edit' u.username %}">Edit Profile</a>
	{% endif %}
{% endblock %}

{% block content %}
<div class="row"> 
			{% if user.username == u.username %}
				<div class='profile-pic' style="background-image: url('/media/{{u.profile.profile_pic}}');"></div>
			{% else %}
				<div class='profile-pic' style="background-image: url('/static/images/placeholders/placeholder-hi.png');"> </div>
			{% endif %}

	<div class="basic-info">
		<div class="list-group">
		  <div class="list-group-item flex-column align-items-start">
		    <div class="d-flex w-100 justify-content-between">
		    </div>
		    <table class="table mb-1">
    			<tr class="first"><td><strong>Username:</strong></td>     <td>{{ u.username }}</td></tr>
    			<tr><td><strong>Bio:</strong></td>          <td>{{ u.profile.bio }}</strong></td></tr>
  				<tr><td><strong>Location:</strong></td>     <td>{{ u.profile.location }}</td></tr>
  				<tr><td><strong>Birth Date:</strong></td>   <td>{{ u.profile.birth_date }}</td></tr>
		    </table>
		  </div>
		</div>

	</div>
</div>

{% endblock %}

Django/wumpworld/templates/signup.html
{% extends 'base.html' %}

{% block page-title %}Sign up{% endblock %}

{% block content %}
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}